build:
  number: 7
  # Remove 'win' from the skip list
  skip: true  # [osx or (python_impl == 'pypy')]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    # Add cmake and ninja for the Windows build
    - cmake
    - ninja
    - make  # [unix]
  host:
    - libtool  # [unix]
    - python
    - numpy
    - scipy
    - qhull
    - mumps-seq
    - libopenblas
  run:
    - numpy
    - scipy
    - qhull
    - mumps-seq
    - libopenblas
    - python